//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiChain.DataAgent {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiChain.DataAgent.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 33333.
        /// </summary>
        internal static string MainnetPort {
            get {
                return ResourceManager.GetString("MainnetPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string MainnetStoragePath {
            get {
                return ResourceManager.GetString("MainnetStoragePath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 44333 的本地化字符串。
        /// </summary>
        internal static string MainnetTrackerPort {
            get {
                return ResourceManager.GetString("MainnetTrackerPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 192.168.1.67 的本地化字符串。
        /// </summary>
        internal static string MainnetTrackerServer {
            get {
                return ResourceManager.GetString("MainnetTrackerServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 44444.
        /// </summary>
        internal static string TestnetPort {
            get {
                return ResourceManager.GetString("TestnetPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage_Test.
        /// </summary>
        internal static string TestnetStoragePath {
            get {
                return ResourceManager.GetString("TestnetStoragePath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 44000 的本地化字符串。
        /// </summary>
        internal static string TestnetTrackerPort {
            get {
                return ResourceManager.GetString("TestnetTrackerPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 192.168.1.67 的本地化字符串。
        /// </summary>
        internal static string TestnetTrackerServer {
            get {
                return ResourceManager.GetString("TestnetTrackerServer", resourceCulture);
            }
        }
    }
}
