//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiChain.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiChain.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 --
        ///-- 由SQLiteStudio v3.1.1 产生的文件 周二 7月 31 16:56:44 2018
        ///--
        ///-- 文本编码：System
        ///--
        ///PRAGMA foreign_keys = off;
        ///BEGIN TRANSACTION;
        ///
        ///-- 表：Accounts
        ///CREATE TABLE IF NOT EXISTS Accounts (
        ///    Id          VARCHAR (64) NOT NULL
        ///                             PRIMARY KEY,
        ///    PrivateKey  VARCHAR (64),
        ///    PublicKey   VARCHAR (64),
        ///    Balance     INTEGER      NOT NULL
        ///                             DEFAULT 0,
        ///    IsDefault   BOOLEAN      NOT NULL
        ///                             DEFAULT 0,
        ///    WatchedOnly BOOLEA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitScript {
            get {
                return ResourceManager.GetString("InitScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename=./fiiichain.db; Mode=ReadWriteCreate;Cache=Shared; 的本地化字符串。
        /// </summary>
        internal static string MainnetConnectionString {
            get {
                return ResourceManager.GetString("MainnetConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename=./fiiichain_test.db; Mode=ReadWriteCreate;Cache=Shared; 的本地化字符串。
        /// </summary>
        internal static string TestnetConnectionString {
            get {
                return ResourceManager.GetString("TestnetConnectionString", resourceCulture);
            }
        }
    }
}
